name: mcd_data_analytics
version: 1.0.0
config-version: 2

profile: mcd_data_analytics_profile

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
  p_full_model_name: ALL
  p_manual_batch_id: 99991231010101
  p_pipeline_name: mcd

flags:
  enable_iceberg_materializations: True

seeds:
  mcd_data_analytics:  
    data:
      +database: "{{ env_var('DBT_MCD_DATABASE')| as_text }}"
      +schema: "{{ env_var('DBT_BRONZE_SCHEMA') | as_text }}"

models:
  mcd_data_analytics:
    bronze:
      +materialized: table
      +database: "{{ env_var('DBT_MCD_DATABASE')| as_text }}"
      +schema: "{{ env_var('DBT_BRONZE_SCHEMA') | as_text }}"
    silver:
      +materialized: table
      +database: "{{ env_var('DBT_MCD_DATABASE')| as_text }}"
      +schema: "{{ env_var('DBT_SILVER_SCHEMA') | as_text }}"
    gold:
      +materialized: table
      +database: "{{ env_var('DBT_MCD_DATABASE')| as_text }}"
      +schema: "{{ env_var('DBT_GOLD_SCHEMA') | as_text }}"